name: upload-coverage-to-codacy
on:
  workflow_run:
    workflows: ["unit-tests"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    name: upload-coverage
    steps:
      - name: Upload Coverage to Codacy
        shell: bash
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/logs/clover.xml